### PR TITLE
Fix SQL query error when threads contain no posts

### PR DESCRIPTION
**Pull request by Ralle**
Hello xfrocks,

As promised, here is the pull request.

"1 = 0" may look weird but it was the most correct way to fix it with as few line edits as possible.

### CODE REVIEW

**Comment by daohoangson** [comment]
Interesting fix. What an odd situation! Thank you.

**Comment by daohoangson** [comment]
While refactoring for XenForo 1.2.0+, I have added a check before calling the `getAllFromGivenUserForPostIds()` so it will no longer being called with an empty array (thread with no posts).

**Comment by Ralle** [comment]
Yeah, odd indeed. I am building a kind of resource system that attaches directly onto threads. This means that there will be no first post. The first post is a comment if anybody wants to comment on it.

Thanks for letting me participate.

**Comment by ghost** [comment]
Ah, that would cause quite a headache. I know first hand some of my add-ons
are going to throw errors all around because of that. Good luck with your
project.

**Pull request merged**
